-- MySQL Script generated by MySQL Workbench
-- Thu Jul 28 09:50:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wtw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wtw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wtw` DEFAULT CHARACTER SET utf8mb4 ;
USE `wtw` ;

-- -----------------------------------------------------
-- Table `wtw`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wtw`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `avatar_url` VARCHAR(500) NULL,
  `created_at` TIMESTAMP NULL,
  `is_moderator` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wtw`.`films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wtw`.`films` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `poster_image` VARCHAR(500) NULL,
  `preview_image` VARCHAR(500) NULL,
  `background_image` VARCHAR(500) NULL,
  `background_color` CHAR(7) NULL,
  `video_link` VARCHAR(500) NULL,
  `preview_video_link` VARCHAR(500) NULL,
  `description` TEXT NULL,
  `rating` DECIMAL(2,1) NULL,
  `run_time` SMALLINT NULL,
  `released` INT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  `imdb_id` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wtw`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wtw`.`comments` (
  `id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `text` TEXT NOT NULL,
  `film_id` INT UNSIGNED NOT NULL,
  `rating` TINYINT UNSIGNED NULL,
  `comment_id` INT NULL,
  `author_id` INT UNSIGNED NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `comment_film_idx` (`film_id` ASC) VISIBLE,
  INDEX `fk_comments_users1_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `comment_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `wtw`.`films` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`author_id`)
    REFERENCES `wtw`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wtw`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wtw`.`genres` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wtw`.`promo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wtw`.`promo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `film_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `promo_film_idx` (`film_id` ASC) VISIBLE,
  CONSTRAINT `promo_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `wtw`.`films` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wtw`.`user_films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wtw`.`user_films` (
  `user_id` INT UNSIGNED NOT NULL,
  `film_id` INT UNSIGNED NOT NULL,
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`user_id`, `film_id`, `id`),
  INDEX `fk_users_has_films_films1_idx` (`film_id` ASC) VISIBLE,
  INDEX `fk_users_has_films_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_films_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `wtw`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_films_films1`
    FOREIGN KEY (`film_id`)
    REFERENCES `wtw`.`films` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wtw`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wtw`.`favorites` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `film_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favorites_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_favorites_films1_idx` (`film_id` ASC) VISIBLE,
  CONSTRAINT `fk_favorites_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `wtw`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_favorites_films1`
    FOREIGN KEY (`film_id`)
    REFERENCES `wtw`.`films` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wtw`.`directors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wtw`.`directors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wtw`.`film_directors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wtw`.`film_directors` (
  `director_id` INT UNSIGNED NOT NULL,
  `film_id` INT UNSIGNED NOT NULL,
  `id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`director_id`, `film_id`, `id`),
  INDEX `fk_directors_has_films_films1_idx` (`film_id` ASC) VISIBLE,
  INDEX `fk_directors_has_films_directors1_idx` (`director_id` ASC) VISIBLE,
  CONSTRAINT `fk_directors_has_films_directors1`
    FOREIGN KEY (`director_id`)
    REFERENCES `wtw`.`directors` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_directors_has_films_films1`
    FOREIGN KEY (`film_id`)
    REFERENCES `wtw`.`films` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wtw`.`stars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wtw`.`stars` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wtw`.`film_stars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wtw`.`film_stars` (
  `star_id` INT UNSIGNED NOT NULL,
  `film_id` INT UNSIGNED NOT NULL,
  `id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`star_id`, `film_id`, `id`),
  INDEX `fk_stars_has_films_films1_idx` (`film_id` ASC) VISIBLE,
  INDEX `fk_stars_has_films_stars1_idx` (`star_id` ASC) VISIBLE,
  CONSTRAINT `fk_stars_has_films_stars1`
    FOREIGN KEY (`star_id`)
    REFERENCES `wtw`.`stars` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_stars_has_films_films1`
    FOREIGN KEY (`film_id`)
    REFERENCES `wtw`.`films` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wtw`.`film_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wtw`.`film_genres` (
  `genre_id` INT UNSIGNED NOT NULL,
  `film_id` INT UNSIGNED NOT NULL,
  `id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`genre_id`, `film_id`, `id`),
  INDEX `fk_genres_has_films_films1_idx` (`film_id` ASC) VISIBLE,
  INDEX `fk_genres_has_films_genres1_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_genres_has_films_genres1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `wtw`.`genres` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_genres_has_films_films1`
    FOREIGN KEY (`film_id`)
    REFERENCES `wtw`.`films` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
